default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: uk-recommendations_development

test:
  <<: *default
  database: uk-recommendations_test

production:
  <<: *default
  database: uk-recommendations_production
